name: ambario
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - libffi=3.4.2
  - liblzma=5.6.3
  - libsqlite=3.47.0
  - libzlib=1.3.1
  - openssl=3.4.0
  - pip=24.3.1
  - python=3.10.16
  - setuptools=75.6.0
  - tk=8.6.13
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - pip:
      - pyaudio==0.2.14
      - pygame==2.6.1
      - opencv-python==4.10.0.84
      - numpy==1.26.0
      - moviepy==2.1.1
      - wave==0.0.2
